import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets build Hulu</h1>

      {/* Header */}

      {/* Navbar */}

      {/* Results */}
    </div>
  )
}
